version: 0.1
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade --user awscli
      - mkdir -p $PYTHON_FOLDER
      - cp -r porper src
      - cd src; pip install -r requirements.txt --no-deps -t $PYTHON_FOLDER; cd ..
  build:
    commands:
      - aws cloudformation package
         --template-file template.yaml
         --s3-bucket $S3_BUCKET_NAME
         --output-template-file samTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
